dist: xenial
compiler:
- gcc
language: python
services:
  - docker
matrix:
  include:
    - env: USE_DEB=true ROS_DISTRO=kinetic BEFORE_SCRIPT='sh .ci_config/dependencies.sh'
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
